AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a CICD pipeline for the NED application
Parameters:
  EcrRepo:
    Description: ''
    NoEcho: false
    Type: String
  GithubBranch:
    Description: ''
    NoEcho: false
    Type: String
  GithubOwner:
    Description: ''
    NoEcho: false
    Type: String
  GithubRepo:
    Description: ''
    NoEcho: false
    Type: String
  GithubToken:
    Description: ''
    NoEcho: true
    Type: String
Resources:
  BuildArtifactsBucket:
    Properties:
      BucketName: !Sub '${AWS::StackName}-cicd-artifacts-bucket'
    Type: AWS::S3::Bucket
  CodeBuildBuildDockerProject:
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Location: !Sub '${BuildArtifactsBucket}/${AWS::StackName}-codebuild-build-docker-cache'
        Type: S3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: IMAGE_REPO
            Value: !Ref 'EcrRepo'
          - Name: AWS_ACCOUNT_ID
            Value: !Sub '${AWS::AccountId}'
        Image: aws/codebuild/docker:17.09.0
        Type: LINUX_CONTAINER
      Name: !Sub '${AWS::StackName}-build-docker-codebuild'
      ServiceRole: !GetAtt 'CodeBuildBuildDockerServiceRole.Arn'
      Source:
        Type: CODEPIPELINE
    Type: AWS::CodeBuild::Project
  CodeBuildBuildDockerServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
        Version: '2012-10-17'
      Path: /managed/
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}-build-docker-codebuild'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}-build-docker-codebuild:*'
            Version: '2012-10-17'
          PolicyName: !Sub 'codebuild-log-access-${AWS::StackName}'
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Effect: Allow
                Resource: !Sub 'arn:aws:s3:::${BuildArtifactsBucket}/*'
            Version: '2012-10-17'
          PolicyName: !Sub 'codebuild-s3-access-${AWS::StackName}'
        - PolicyDocument:
            Statement:
              - Action:
                  - events:PutEvents
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: !Sub 'codebuild-notification-putevent-${AWS::StackName}'
        - PolicyDocument:
            Statement:
              - Action:
                  - ecr:*
                Effect: Allow
                Resource:
                  - '*'
            Version: '2012-10-17'
          PolicyName: access-ecr
        - PolicyDocument:
            Statement:
              - Action:
                  - ssm:*
                Effect: Allow
                Resource:
                  - '*'
            Version: '2012-10-17'
          PolicyName: access-ssm
      RoleName: !Sub '${AWS::StackName}-codebuild-build-docker-service-role'
    Type: AWS::IAM::Role
  CodeBuildCfnDeployProject:
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Location: !Sub '${BuildArtifactsBucket}/${AWS::StackName}-codebuild-deploy-cfn-cache'
        Type: S3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: IMAGE_REPO
            Value: !Ref 'EcrRepo'
          - Name: AWS_ACCOUNT_ID
            Value: !Sub '${AWS::AccountId}'
        Image: aws/codebuild/docker:17.09.0
        Type: LINUX_CONTAINER
      Name: !Sub '${AWS::StackName}-deploy-cfn-codebuild'
      ServiceRole: !GetAtt 'CodeBuildCfnDeployRole.Arn'
      Source:
        BuildSpec: infrastructure/buildspec.yml
        Type: CODEPIPELINE
    Type: AWS::CodeBuild::Project
  CodeBuildCfnDeployRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/CloudWatchEventsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: /managed/
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}-deploy-cfn-codebuild'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}-deploy-cfn-codebuild:*'
            Version: '2012-10-17'
          PolicyName: !Sub 'codebuild-log-access-${AWS::StackName}'
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Effect: Allow
                Resource: !Sub 'arn:aws:s3:::${BuildArtifactsBucket}/*'
            Version: '2012-10-17'
          PolicyName: !Sub 'codebuild-s3-access-${AWS::StackName}'
        - PolicyDocument:
            Statement:
              - Action:
                  - events:PutEvents
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: !Sub 'codebuild-notification-putevent-${AWS::StackName}'
        - PolicyDocument:
            Statement:
              - Action:
                  - cloudformation:*
                Effect: Allow
                Resource:
                  - '*'
            Version: '2012-10-17'
          PolicyName: access-cloudformation
        - PolicyDocument:
            Statement:
              - Action:
                  - iam:*
                Effect: Allow
                Resource:
                  - '*'
            Version: '2012-10-17'
          PolicyName: access-iam
        - PolicyDocument:
            Statement:
              - Action:
                  - ssm:*
                Effect: Allow
                Resource:
                  - '*'
            Version: '2012-10-17'
          PolicyName: access-ssm
      RoleName: !Sub '${AWS::StackName}-codebuild-deploy-cfn-service-role'
    Type: AWS::IAM::Role
  CodePipelinePipeline:
    Properties:
      ArtifactStore:
        Location: !Ref 'BuildArtifactsBucket'
        Type: S3
      Name: !Sub '${AWS::StackName}-default-pipeline'
      RoleArn: !GetAtt 'CodePipelineServiceRole.Arn'
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Branch: !Ref 'GithubBranch'
                OAuthToken: !Ref 'GithubToken'
                Owner: !Ref 'GithubOwner'
                Repo: !Ref 'GithubRepo'
              Name: get-source
              OutputArtifacts:
                - Name: source-zip
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref 'CodeBuildBuildDockerProject'
              InputArtifacts:
                - Name: source-zip
              Name: codebuild-build-docker
              OutputArtifacts:
                - Name: built-zip
              RunOrder: 1
          Name: Build
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref 'CodeBuildCfnDeployProject'
              InputArtifacts:
                - Name: source-zip
              Name: codebuild-cfn-deploy
              OutputArtifacts:
                - Name: template
              RunOrder: 1
          Name: Deploy
    Type: AWS::CodePipeline::Pipeline
  CodePipelineServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
        Version: '2012-10-17'
      Path: /managed/
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:PutObject
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:s3:::${BuildArtifactsBucket}'
                  - !Sub 'arn:aws:s3:::${BuildArtifactsBucket}/*'
            Version: '2012-10-17'
          PolicyName: !Sub 'codepipeline-s3artifact-access-${AWS::StackName}-default'
        - PolicyDocument:
            Statement:
              - Action: iam:PassRole
                Effect: Allow
                Resource:
                  - !GetAtt 'CodeBuildBuildDockerServiceRole.Arn'
                  - !GetAtt 'CodeBuildCfnDeployRole.Arn'
            Version: '2012-10-17'
          PolicyName: !Sub 'codepipeline-passrole-access-${AWS::StackName}-default'
        - PolicyDocument:
            Statement:
              - Action:
                  - codebuild:StartBuild
                  - codebuild:StopBuild
                  - codebuild:BatchGetBuilds
                Effect: Allow
                Resource:
                  - !GetAtt 'CodeBuildBuildDockerProject.Arn'
                  - !GetAtt 'CodeBuildCfnDeployProject.Arn'
            Version: '2012-10-17'
          PolicyName: !Sub 'codepipeline-build-access-${AWS::StackName}-default'
      RoleName: !Sub 'codepipeline-service-role-${AWS::StackName}-default'
    Type: AWS::IAM::Role
